name: pipe1

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: stage1
  jobs:
      - job: test2
        displayName: test
        steps:
        - task: Powershell@2
          inputs:
              targetType: inline
              script: |
                Write-Host "Hello World!"
